[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
m4a_protocol = "7NNuzG9sACEcwT6bL3TxmnScBbvDARZZjE4tdGZoz5Gm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"
#wallet = "usb://ledger"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"